/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesChoosingSaccoSoftwareRouteImport } from './routes/guides.choosing-sacco-software'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppEscalationsRouteImport } from './routes/_app/escalations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppLoansIndexRouteImport } from './routes/_app/loans/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppLoansSimulatorRouteImport } from './routes/_app/loans/simulator'
import { Route as AppLoansApplyRouteImport } from './routes/_app/loans/apply'
import { Route as AppLoansLoanIdRouteImport } from './routes/_app/loans/$loanId'
import { Route as AppAdminSlaRouteImport } from './routes/_app/admin.sla'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin.reports'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin.policies'
import { Route as AppAdminImportRouteImport } from './routes/_app/admin.import'
import { Route as AppAdminEscalationsRouteImport } from './routes/_app/admin.escalations'
import { Route as AppAdminBoardRouteImport } from './routes/_app/admin.board'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin.audit'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesChoosingSaccoSoftwareRoute =
  GuidesChoosingSaccoSoftwareRouteImport.update({
    id: '/guides/choosing-sacco-software',
    path: '/guides/choosing-sacco-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalationsRoute = AppEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppLoansSimulatorRoute = AppLoansSimulatorRouteImport.update({
  id: '/loans/simulator',
  path: '/loans/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansApplyRoute = AppLoansApplyRouteImport.update({
  id: '/loans/apply',
  path: '/loans/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansLoanIdRoute = AppLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSlaRoute = AppAdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminImportRoute = AppAdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEscalationsRoute = AppAdminEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBoardRoute = AppAdminBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/statements': typeof AppStatementsRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/choosing-sacco-software': typeof GuidesChoosingSaccoSoftwareRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/board': typeof AppAdminBoardRoute
  '/admin/escalations': typeof AppAdminEscalationsRoute
  '/admin/import': typeof AppAdminImportRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/sla': typeof AppAdminSlaRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans/simulator': typeof AppLoansSimulatorRoute
  '/admin/': typeof AppAdminIndexRoute
  '/loans/': typeof AppLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/statements': typeof AppStatementsRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/choosing-sacco-software': typeof GuidesChoosingSaccoSoftwareRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/board': typeof AppAdminBoardRoute
  '/admin/escalations': typeof AppAdminEscalationsRoute
  '/admin/import': typeof AppAdminImportRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/sla': typeof AppAdminSlaRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans/simulator': typeof AppLoansSimulatorRoute
  '/admin': typeof AppAdminIndexRoute
  '/loans': typeof AppLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escalations': typeof AppEscalationsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/statements': typeof AppStatementsRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/choosing-sacco-software': typeof GuidesChoosingSaccoSoftwareRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/board': typeof AppAdminBoardRoute
  '/_app/admin/escalations': typeof AppAdminEscalationsRoute
  '/_app/admin/import': typeof AppAdminImportRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/sla': typeof AppAdminSlaRoute
  '/_app/loans/$loanId': typeof AppLoansLoanIdRoute
  '/_app/loans/apply': typeof AppLoansApplyRoute
  '/_app/loans/simulator': typeof AppLoansSimulatorRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/loans/': typeof AppLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/workflow'
    | '/admin'
    | '/approvals'
    | '/dashboard'
    | '/escalations'
    | '/notifications'
    | '/profile'
    | '/statements'
    | '/api/chat'
    | '/guides/choosing-sacco-software'
    | '/admin/audit'
    | '/admin/board'
    | '/admin/escalations'
    | '/admin/import'
    | '/admin/policies'
    | '/admin/reports'
    | '/admin/sla'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/loans/simulator'
    | '/admin/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/workflow'
    | '/approvals'
    | '/dashboard'
    | '/escalations'
    | '/notifications'
    | '/profile'
    | '/statements'
    | '/api/chat'
    | '/guides/choosing-sacco-software'
    | '/admin/audit'
    | '/admin/board'
    | '/admin/escalations'
    | '/admin/import'
    | '/admin/policies'
    | '/admin/reports'
    | '/admin/sla'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/loans/simulator'
    | '/admin'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/workflow'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/escalations'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/statements'
    | '/api/chat'
    | '/guides/choosing-sacco-software'
    | '/_app/admin/audit'
    | '/_app/admin/board'
    | '/_app/admin/escalations'
    | '/_app/admin/import'
    | '/_app/admin/policies'
    | '/_app/admin/reports'
    | '/_app/admin/sla'
    | '/_app/loans/$loanId'
    | '/_app/loans/apply'
    | '/_app/loans/simulator'
    | '/_app/admin/'
    | '/_app/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesChoosingSaccoSoftwareRoute: typeof GuidesChoosingSaccoSoftwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/choosing-sacco-software': {
      id: '/guides/choosing-sacco-software'
      path: '/guides/choosing-sacco-software'
      fullPath: '/guides/choosing-sacco-software'
      preLoaderRoute: typeof GuidesChoosingSaccoSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalations': {
      id: '/_app/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof AppEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/loans/simulator': {
      id: '/_app/loans/simulator'
      path: '/loans/simulator'
      fullPath: '/loans/simulator'
      preLoaderRoute: typeof AppLoansSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/apply': {
      id: '/_app/loans/apply'
      path: '/loans/apply'
      fullPath: '/loans/apply'
      preLoaderRoute: typeof AppLoansApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$loanId': {
      id: '/_app/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AppLoansLoanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sla': {
      id: '/_app/admin/sla'
      path: '/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AppAdminSlaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/import': {
      id: '/_app/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AppAdminImportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/escalations': {
      id: '/_app/admin/escalations'
      path: '/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AppAdminEscalationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/board': {
      id: '/_app/admin/board'
      path: '/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AppAdminBoardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBoardRoute: typeof AppAdminBoardRoute
  AppAdminEscalationsRoute: typeof AppAdminEscalationsRoute
  AppAdminImportRoute: typeof AppAdminImportRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSlaRoute: typeof AppAdminSlaRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBoardRoute: AppAdminBoardRoute,
  AppAdminEscalationsRoute: AppAdminEscalationsRoute,
  AppAdminImportRoute: AppAdminImportRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSlaRoute: AppAdminSlaRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscalationsRoute: typeof AppEscalationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppLoansLoanIdRoute: typeof AppLoansLoanIdRoute
  AppLoansApplyRoute: typeof AppLoansApplyRoute
  AppLoansSimulatorRoute: typeof AppLoansSimulatorRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscalationsRoute: AppEscalationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppLoansLoanIdRoute: AppLoansLoanIdRoute,
  AppLoansApplyRoute: AppLoansApplyRoute,
  AppLoansSimulatorRoute: AppLoansSimulatorRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkflowRoute: WorkflowRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesChoosingSaccoSoftwareRoute: GuidesChoosingSaccoSoftwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
