/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppLoansIndexRouteImport } from './routes/_app/loans/index'
import { Route as AppLoansApplyRouteImport } from './routes/_app/loans/apply'
import { Route as AppLoansLoanIdRouteImport } from './routes/_app/loans/$loanId'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin.reports'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin.policies'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansApplyRoute = AppLoansApplyRouteImport.update({
  id: '/loans/apply',
  path: '/loans/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansLoanIdRoute = AppLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workflow': typeof WorkflowRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/statements': typeof AppStatementsRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans/': typeof AppLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workflow': typeof WorkflowRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/statements': typeof AppStatementsRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans': typeof AppLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/workflow': typeof WorkflowRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/loans/$loanId': typeof AppLoansLoanIdRoute
  '/_app/loans/apply': typeof AppLoansApplyRoute
  '/_app/loans/': typeof AppLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workflow'
    | '/admin'
    | '/approvals'
    | '/dashboard'
    | '/profile'
    | '/statements'
    | '/admin/policies'
    | '/admin/reports'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/workflow'
    | '/admin'
    | '/approvals'
    | '/dashboard'
    | '/profile'
    | '/statements'
    | '/admin/policies'
    | '/admin/reports'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/workflow'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/statements'
    | '/_app/admin/policies'
    | '/_app/admin/reports'
    | '/_app/loans/$loanId'
    | '/_app/loans/apply'
    | '/_app/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/apply': {
      id: '/_app/loans/apply'
      path: '/loans/apply'
      fullPath: '/loans/apply'
      preLoaderRoute: typeof AppLoansApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$loanId': {
      id: '/_app/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AppLoansLoanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppLoansLoanIdRoute: typeof AppLoansLoanIdRoute
  AppLoansApplyRoute: typeof AppLoansApplyRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppLoansLoanIdRoute: AppLoansLoanIdRoute,
  AppLoansApplyRoute: AppLoansApplyRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
